name: Schedule Test Runs

on:
  schedule:
    # Modify this to specify when the job should run. The below is every Sunday at 12 AM GMT
    - cron: '0 0 * * 0'
  # Allows the workflow to be run manually through the GitHub UI
  workflow_dispatch:

jobs:
  schedule_tests:
    strategy:
      matrix:
        sf_org_alias: [UAT]

    env:
        ENVIRONMENT: ${{ matrix.sf_org_alias }}

    runs-on: ubuntu-latest

    steps:

    - run: echo what is the secret ${{ secrets[format('SFDX_{0}_URL', env.ENVIRONMENT)] }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
        mkdir ~/sfdx
        tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
        echo "$HOME/sfdx/bin" >> $GITHUB_PATH
        ~/sfdx/bin/sfdx version

    - name: Populate auth file with SFDX_URL secret
      run: echo ${{ secrets[format('SFDX_{0}_URL', env.ENVIRONMENT)] }} > ./SFDX_${{ matrix.sf_org_alias }}_URL.txt

    - name: Authenticate to Org
      #run: sfdx org:login:sfdx-url --alias ${{ matrix.sf_org_alias }} --sfdx-url-file ./.github/workflows/SFDX_${{ matrix.sf_org_alias }}_URL.txt
      run: sfdx auth:sfdxurl:store -f ./SFDX_${{ matrix.sf_org_alias }}_URL.txt -s -a ${{ matrix.sf_org_alias }}

    - name: Run all tests and store test run Id
      run: |
        sfdx apex run test --target-org demosbox.slavak@redmountainweightloss.com --test-level RunLocalTests --result-format human > ./id.txt
        # sfdx apex run test --target-org demosbox.slavak@redmountainweightloss.com --test-level RunSpecifiedTests --tests GeoNearestTest --tests ServiceAppointmentControllerTest --tests OrderEntryProcessorTest --tests MicrobatchSelfRegControllerTest --tests CommissionByUserTriggerHandlerTest --tests CommissionByProductTriggerHandlerTest --tests contentDocumentLinkTriggerHandlerTest --tests ConvertDateToDatetimeFlowActionTest --tests MedSpaNoteTriggerHandlerTest --tests ClinicalEncounterTriggerTest --tests ClientAppointmentProgressControllerTest --tests AddEmployeeLookupController_Test --tests TotalAlertControllerTest --tests FileUploadImproved_Test --tests customServiceAppointmentCreationTest --tests ConfirmServiceAppoinment_Test --tests ProviderRecommendationListControllerTest --tests DatetimeUtilFlowActionTest --tests ManageCurrentTaskControllerTest --tests FoodServingHomeTest --tests ProductRecommendationActionTest --tests AppointmentTodayControllerTest --tests PrepaidListControllerTest --tests UniversalBlocksTest --tests CreateMedSpaNotesControllerTest --tests CreateSOAPNotesControllerTest --tests ReusableLookupControllerTest --tests soapNoteComponentTest --tests GoogleRecaptchaHandlerTest --tests Base64ToAttachmentTest --tests LightningSelfRegisterControllerTest --tests SendNotificationToPatient_Test --tests healthConditionRecordListTest --tests UpdatePatientWeightOnPatientPortalTest --tests AuthorNoteHandlerTest --tests serviceAppointmentTrigger_Test --result-format human > ./id.txt
        echo "$(node ./extractId.js)" > ${{ matrix.sf_org_alias }}_test_run_id.txt

    - name: Upload the test run Id as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.sf_org_alias }}_test_run_id
        path: ${{ matrix.sf_org_alias }}_test_run_id.txt
